# This is a basic workflow to help you get started with Actions

name: AUTO_DEPLOY

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the gh-pages branch
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # chmod +x ./install.sh
      # chmod +x ./dev.sh 
      # chmod +x ./app.sh 
      # chmod +x ./copy.sh 

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ./install.sh

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ./app.sh

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ./clean.sh

      # rm -rf -Y bug, rm -rf & rimraf ???

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ./copy.sh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo install finished ✅,
          echo build finished ✅,
          echo deploy finished ✅.
          
      # todos...




#  ./app.sh && ./copy.sh
